#!/bin/bash

echo "**********************************************"
echo "*                                            *"
echo "*       MyFixApp v0.1    Hoş Geldiniz!       *"
echo "*                                            *"
echo "*      İyi günler dilerim, $USER!            "
echo "*                                            *"
echo "*     Güncel Tarih ve Saat: $(date)          "
echo "*     Sistem Süresi: $(uptime -p)            *"
echo "*                                            *"
echo "*             By Oguzhan DUYAR               *"
echo "*                                            *"
echo "**********************************************"


# Auto update and upgrade
echo “Sistemin güncellenmesi ve yükseltilmesi...”
sudo apt-get update -y && sudo apt-get upgrade -y

# Auto remove unnecessary packages
echo “Gereksiz paketleri kaldırıyorum...”
sudo apt-get autoremove -y

# Auto clean up the package cache
echo “Paket önbelleği temizleniyor...”
sudo apt-get clean

# Clean up orphaned packages
echo “Öksüz paketleri temizniyor...”
sudo apt-get autoclean -y

# Remove old kernels (keeping the current and the previous one)
echo “Eski çekirdekleri çıkarıyorum...”
sudo apt-get purge $(dpkg -l 'linux-image-[0-9]*' | awk '/^ii/{ print $2}' | grep -v `uname -r | cut -d"-" -f1,2`)

# Delete unnecessary files in /var/log
echo “Geçici log dosyaları temizleniyor...”
sudo find /var/log -type f -name "*.log" -delete

# Delete files from the trash
echo “Çöpü boşaltıyorum...”
rm -rf ~/.local/share/Trash/*


# Display disk usage
echo “Disk kullanımı görüntüleniyor...”
df -h

echo “Bakım tamamlandı.”
# Wait for user to press a key before closing
read -n 1 -s -r -p “...”